[build]
  command = "cp config/prompts.template.json config/prompts.json && next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["@netlify/functions"]

[[edge_functions]]
  function = "api/*"
  path = "/api/*"

[[edge_functions]]
  function = "app/*"
  path = "/app/*"

# Function-specific configurations
[functions."api/openai/*"]
  external_node_modules = ["openai"]
  included_files = ["config/prompts.json"]

[functions."api/coingecko/*"]
  external_node_modules = ["node-fetch"]

[functions."api/solana/*"]
  external_node_modules = ["@solana/web3.js", "@solana/spl-token"]

# Exclude development files
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 