[build]
  command = "cp config/prompts.template.json config/prompts.json && next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  function = "openai"
  path = "/api/openai/*"

[[edge_functions]]
  function = "coingecko"
  path = "/api/coingecko/*"

[[edge_functions]]
  function = "solana"
  path = "/api/solana/*"

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 