[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  external_node_modules = ["@sparticuz/chromium"]
  node_bundler = "esbuild"
  included_files = ["node_modules/@sparticuz/chromium-*/**"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/scrape-news"
  status = 200 