[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["axios", "jsdom"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/scrape-news"
  status = 200 