[build]
  command = "cp config/prompts.template.json config/prompts.json && next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = [
    "@netlify/functions",
    "crypto-js",
    "@solana/web3.js",
    "@solana/spl-token",
    "@solana/wallet-adapter-base",
    "@solana/wallet-adapter-react",
    "@solana/wallet-adapter-react-ui",
    "@solana/wallet-adapter-wallets",
    "openai"
  ]

[[edge_functions]]
  function = "api/*"
  path = "/api/*"

# Split dependencies between edge functions and regular functions
[functions."api/openai/*"]
  external_node_modules = ["openai"]

[functions."api/coingecko/*"]
  external_node_modules = ["node-fetch"]

[functions."api/solana/*"]
  external_node_modules = [
    "@solana/web3.js",
    "@solana/spl-token"
  ]

# Exclude test and development files
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 