[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[[edge_functions]]
  function = "api/*"
  path = "/api/*"

# Function bundle optimizations
[functions."*"]
  included_files = []
  external_node_modules = [
    "@netlify/functions",
    "crypto-js",
    "@solana/web3.js",
    "@solana/spl-token",
    "@solana/wallet-adapter-base",
    "@solana/wallet-adapter-react",
    "@solana/wallet-adapter-react-ui",
    "@solana/wallet-adapter-wallets",
    "openai",
    "express",
    "express-rate-limit",
    "ioredis",
    "rate-limit-redis",
    "@upstash/redis"
  ] 