[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  external_node_modules = ["@sparticuz/chromium"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/scrape-news"
  status = 200 