[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio"]

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/scrape-news"
  status = 200 