[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[functions."*"]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/scrape-news"
  status = 200 