[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[[edge_functions]]
  function = "api/*"
  path = "/api/*"

# Function bundle optimizations
[functions."*"]
  included_files = []
  external_node_modules = [
    "@netlify/functions",
    "crypto-js"
  ] 