[build]
  command = "cp config/prompts.template.json config/prompts.json && next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_DISABLE_SSR = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["config/prompts.json"]

[functions."*"]
  external_node_modules = ["@netlify/functions"]

[functions.openai]
  external_node_modules = ["openai"]

[functions.coingecko]
  external_node_modules = ["node-fetch"]

[functions.solana]
  external_node_modules = ["@solana/web3.js", "@solana/spl-token"]

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 